spring:
  application:
    name: gateway-reactive

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: borrow-service
          uri: lb://borrow-service
          predicates:
            - Path=/borrow/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
